auto:        true
server:      true

server_port: 4000
baseurl:     /antwort
url:         http://localhost:4000

source:      .
destination: ./_site
permalink:   none

repo_url:   http://github.com/internations/antwort
pages_url:  http://internations.github.com/antwort